---
title: "Data wrangling in tidyr"
author: "Michelle Lam"
date: "2022-08-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(tidyverse)
library(here)
library(janitor)
```


## Read in WB data files

```{r}
# Read in wb_indicators.csv file and convert the missing values using the na function
wb_indicators <- read_csv(here("data", "wb_indicators.csv"), na = c("..", ""))

# Read in metadata
wb_metadata <- read_csv(here("data", "wb_indicators_metadata.csv"))
```

## Tidy up my data

### pivot_longer to get years into a single column

```{r}
wb_indicators_long <- wb_indicators |> 
  pivot_longer(cols = '2001 [YR2001]':'2020 [YR2020]',
               names_to = "year",
               values_to = "indicator_value")
```

### separate to clean up the year column

```{r}
wb_clean <- wb_indicators_long |> 
  separate(col = year, into = c("year", "year_chr"), sep = " ") |> 
  select(-year_chr, -'Country Code', -'Series Code') |> 
  mutate(year = as.numeric(year)) |> 
  drop_na('Series Name') |> 
  pivot_wider(names_from = 'Series Name',
              values_from = 'indicator_value')

# can also create a new column with the mutate function by specifying new column name
# drop_na remove rows where series name is NA
# use unique() to see unique values in column 
# Widen the variables currently trapped in 'Series Name' to be spread across multiple columns, and get the values that populated the columns from 'indicator_value'

# rename columns with names() function, not a pipe-able function
names(wb_clean) <- c("country", "year", "access_clean_fuels_pp", "access_electricity_pp", "co2_emissions_kt", "fossil_fuel_cons_pct", "water_stress")

# rename columns using the rename() function
wb_clean_2 <- wb_clean |> 
  rename(my_year = year)

# filter by subset of countries
wb_subset <- wb_clean |> 
  filter(country %in% c("Algeria", "Barbados", "Bulgaria", "Chile"))

# create graph
ggplot(data = wb_subset, aes(x = year, y = co2_emissions_kt)) +
  geom_line(aes(color = country)) +
  facet_wrap(~country)
```

## filtering rows

Exammple 1: Filter to only keep exact matches

```{r}
ex_1 <- starwars |> 
  filter(height > 180)
```

```{r}
ex_2 <- starwars |> 
  filter(eye_color == "blue")
```

```{r}
# Make a subset that only contains rows where the homeworld is Naboo
ex_3 <- starwars |> 
  filter(homeworld == "Naboo")
```


Examples: filtering to satisfy multiple conditions

```{r}
ex_4 <- starwars |> 
  filter(height > 180 & homeworld == "Tatooine")
```

```{r}
# Create a subset where the hair color is brown and species is human
ex_5 <- starwars |> 
  filter(hair_color == "brown" & species == "Human")
```

### filtering OR statements

```{r}
ex_6 <- starwars |> 
  filter(height > 180 | eye_color == "yellow")
```

```{r}
# create a subset that keeps rows if homeworld is Endor OR species is droid
ex_7 <- starwars |> 
  filter(homeworld == "Endor" | species == "Droid")
```

```{r}
# referring to single variables values with OR operator
ex_8 <- starwars |> 
  filter(eye_color == "blue" | eye_color == "brown" | eye_color == "red")

# Or the exact same thing efficiently 
ex_9 <- starwars |> 
  filter(eye_color %in% c("blue", "brown", "red"))

# THIS IS NEVER WHAT YOU WANT TO DO
# This is asking does the first row match blue, does the second row match brown, does the third row match red, does the fourth row match blue, does the fifth row match brown, does the sixth row match red, etc. 
ex_10 <- starwars |> 
  filter(eye_color == c("blue", "brown", "red"))

# Create a subset where the homeworld is Endor OR Tatooine OR Naboo AND height < 150
# comma will read as an AND for filter function
ex_11 <- starwars |> 
  filter(homeworld %in% c("Endor", "Tatooine", "Naboo"),
         height < 150)
```

Examples with the negate!

```{r}
ex_12 <- starwars |> 
  filter(species != "Human")

ex_13 <- starwars |> 
  filter(!species %in% c("Human", "Ewok", "Wookiee"))
```

## `select()`: select or exclude columns

```{r}
# Select by name
ex_14 <- wb_clean |> 
  select(country, year, co2_emissions_kt)

# range of columns by name or position
ex_15 <- wb_clean |> 
  select(year:fossil_fuel_cons_pct)

# Exclude columns from a range
# negate (!) is for a logical statement: true, false
ex_16 <- wb_clean |> 
  select(year:fossil_fuel_cons_pct, -access_electricity_pp)
```


```{r}
# multiple pipe steps together
ex_17 <- wb_clean |> 
  filter (country %in% c("Bolivia", "Chile", "Mexico")) |> 
  select(country:fossil_fuel_cons_pct)
```

```{r}
# use select to select specific columns, rename the columns, and reorder the columns
ex_18 <- wb_clean |> 
  select(year_new = year, 
         emissions = co2_emissions_kt, 
         country_name = country)

# Select only columns for country, year, and water stress and reorder them as year, country water stress, then filter to only include observations for any 3 countries of your choice
ex_19 <- wb_clean |> 
  select(year, country, water_stress) |> 
  filter(country %in% c("Argentina", "Belgium", "Cambodia"))
```

